apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: serviceb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceb
  labels:
    app: serviceB
    service: serviceb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceB
      service: serviceb
  template:
    metadata:
      labels:
        app: serviceB
        service: serviceb
    spec:
      serviceAccountName: serviceb
      
      containers:
      - name: serviceb-container
        image: hhana982/serviceb:1.<version>
        ports:
        - containerPort: 5000
        
        env: 